version: '3'
services:
  mosquitto:
    image: eclipse-mosquitto
    networks:
      - iot_network
    ports:
      - "1883:1883"
    restart: unless-stopped
    volumes:
      - mosquitto_data:/mosquitto/data           # Persist data for Mosquitto
      - mosquitto_logs:/mosquitto/log             # Persist logs for Mosquitto
      - ./mosquitto/mosquitto.conf:/mosquitto/config/mosquitto.conf
#      - ~/Plume_Project/config/mosquitto.conf:/mosquitto/config/mosquitto.conf
#    command: /mosquitto/config/mosquitto.conf

  influxdb:
    image: influxdb:1.11.7
    networks:
      - iot_network
    environment:
      - INFLUXDB_DB=iot_data
      - INFLUXDB_ADMIN_USER=admin
      - INFLUXDB_ADMIN_PASSWORD=adminpassword
    ports:
      - "8086:8086"
    restart: unless-stopped
    volumes:
      - influxdb_data:/var/lib/influxdb          # Persist data for InfluxDB

  grafana:
    image: grafana/grafana
    networks:
      - iot_network
    ports:
      - "3000:3000"
    restart: unless-stopped
    volumes:
      - grafana_data:/var/lib/grafana            # Persist data for Grafana

  nodered:
    image: nodered/node-red
    networks:
      - iot_network
    ports:
      - "1880:1880"
    restart: unless-stopped
    volumes:
      - nodered_data:/data                       # Persist data for Node-RED

networks:
  iot_network:
    driver: bridge

volumes:
  mosquitto_data:
  mosquitto_logs:
  influxdb_data:
  grafana_data:
  nodered_data:

